// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY `Serializers/PrimitiveSerializer.tt`. DO NOT CHANGE IT.
// </auto-generated>
#nullable enable
namespace FakeExcelSerializer.Tests
{
    public partial class PrimitiveSerializerTest 
    {
        [Fact]
        public void Serializer_Decimal()
        {
            var value1 = Decimal.MinValue;
            var value2 = Decimal.MaxValue;
            RunNumberTest(value1, value2, ExcelSerializerOptions.Default);
        }
        [Fact]
        public void Serializer_Double()
        {
            var value1 = Double.MinValue;
            var value2 = Double.MaxValue;
            RunNumberTest(value1, value2, ExcelSerializerOptions.Default);
        }
        [Fact]
        public void Serializer_Single()
        {
            var value1 = Single.MinValue;
            var value2 = Single.MaxValue;
            RunNumberTest(value1, value2, ExcelSerializerOptions.Default);
        }
        [Fact]
        public void Serializer_Int16()
        {
            var value1 = Int16.MinValue;
            var value2 = Int16.MaxValue;
            RunNumberTest(value1, value2, ExcelSerializerOptions.Default);
        }
        [Fact]
        public void Serializer_UInt16()
        {
            var value1 = UInt16.MinValue;
            var value2 = UInt16.MaxValue;
            RunNumberTest(value1, value2, ExcelSerializerOptions.Default);
        }
    }
}