// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY `TupleTest.tt`. DO NOT CHANGE IT.
// </auto-generated>
#nullable enable
namespace FakeExcelSerializer.Tests;

public partial class TupleSerializersTest
{
    [Fact]
    public void Serializer_tuple1()
    {
        var t = Tuple.Create(1);
        RunTest(t, "<c t=\"n\" s=\"5\"><v>1</v></c>", ExcelSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple2()
    {
        var t = Tuple.Create(1, 2);
        RunTest(t, "<c t=\"n\" s=\"5\"><v>1</v></c><c t=\"n\" s=\"5\"><v>2</v></c>", ExcelSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple3()
    {
        var t = Tuple.Create(1, 2, 3);
        RunTest(t, "<c t=\"n\" s=\"5\"><v>1</v></c><c t=\"n\" s=\"5\"><v>2</v></c><c t=\"n\" s=\"5\"><v>3</v></c>", ExcelSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple4()
    {
        var t = Tuple.Create(1, 2, 3, 4);
        RunTest(t, "<c t=\"n\" s=\"5\"><v>1</v></c><c t=\"n\" s=\"5\"><v>2</v></c><c t=\"n\" s=\"5\"><v>3</v></c><c t=\"n\" s=\"5\"><v>4</v></c>", ExcelSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple5()
    {
        var t = Tuple.Create(1, 2, 3, 4, 5);
        RunTest(t, "<c t=\"n\" s=\"5\"><v>1</v></c><c t=\"n\" s=\"5\"><v>2</v></c><c t=\"n\" s=\"5\"><v>3</v></c><c t=\"n\" s=\"5\"><v>4</v></c><c t=\"n\" s=\"5\"><v>5</v></c>", ExcelSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple6()
    {
        var t = Tuple.Create(1, 2, 3, 4, 5, 6);
        RunTest(t, "<c t=\"n\" s=\"5\"><v>1</v></c><c t=\"n\" s=\"5\"><v>2</v></c><c t=\"n\" s=\"5\"><v>3</v></c><c t=\"n\" s=\"5\"><v>4</v></c><c t=\"n\" s=\"5\"><v>5</v></c><c t=\"n\" s=\"5\"><v>6</v></c>", ExcelSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple7()
    {
        var t = Tuple.Create(1, 2, 3, 4, 5, 6, 7);
        RunTest(t, "<c t=\"n\" s=\"5\"><v>1</v></c><c t=\"n\" s=\"5\"><v>2</v></c><c t=\"n\" s=\"5\"><v>3</v></c><c t=\"n\" s=\"5\"><v>4</v></c><c t=\"n\" s=\"5\"><v>5</v></c><c t=\"n\" s=\"5\"><v>6</v></c><c t=\"n\" s=\"5\"><v>7</v></c>", ExcelSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple8()
    {
        var t = Tuple.Create(1, 2, 3, 4, 5, 6, 7, 8);
        RunTest(t, "<c t=\"n\" s=\"5\"><v>1</v></c><c t=\"n\" s=\"5\"><v>2</v></c><c t=\"n\" s=\"5\"><v>3</v></c><c t=\"n\" s=\"5\"><v>4</v></c><c t=\"n\" s=\"5\"><v>5</v></c><c t=\"n\" s=\"5\"><v>6</v></c><c t=\"n\" s=\"5\"><v>7</v></c><c t=\"n\" s=\"5\"><v>8</v></c>", ExcelSerializerOptions.Default);
    }
}