// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY `Serializers/PrimitiveSerializer.tt`. DO NOT CHANGE IT.
// </auto-generated>
#nullable enable
namespace FlatXlsx.Serializers
{
    public sealed class BooleanXlsxSerializer : IXlsxSerializer<Boolean>
    {        
		public void WriteTitle(XlsxCellWriter writer, Boolean value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, Boolean value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class ByteXlsxSerializer : IXlsxSerializer<Byte>
    {        
		public void WriteTitle(XlsxCellWriter writer, Byte value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, Byte value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class SByteXlsxSerializer : IXlsxSerializer<SByte>
    {        
		public void WriteTitle(XlsxCellWriter writer, SByte value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, SByte value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class DecimalXlsxSerializer : IXlsxSerializer<Decimal>
    {        
		public void WriteTitle(XlsxCellWriter writer, Decimal value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, Decimal value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class DoubleXlsxSerializer : IXlsxSerializer<Double>
    {        
		public void WriteTitle(XlsxCellWriter writer, Double value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, Double value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class SingleXlsxSerializer : IXlsxSerializer<Single>
    {        
		public void WriteTitle(XlsxCellWriter writer, Single value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, Single value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class Int32XlsxSerializer : IXlsxSerializer<Int32>
    {        
		public void WriteTitle(XlsxCellWriter writer, Int32 value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, Int32 value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class UInt32XlsxSerializer : IXlsxSerializer<UInt32>
    {        
		public void WriteTitle(XlsxCellWriter writer, UInt32 value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, UInt32 value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class Int64XlsxSerializer : IXlsxSerializer<Int64>
    {        
		public void WriteTitle(XlsxCellWriter writer, Int64 value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, Int64 value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class UInt64XlsxSerializer : IXlsxSerializer<UInt64>
    {        
		public void WriteTitle(XlsxCellWriter writer, UInt64 value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, UInt64 value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class Int16XlsxSerializer : IXlsxSerializer<Int16>
    {        
		public void WriteTitle(XlsxCellWriter writer, Int16 value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, Int16 value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

    public sealed class UInt16XlsxSerializer : IXlsxSerializer<UInt16>
    {        
		public void WriteTitle(XlsxCellWriter writer, UInt16 value, XlsxSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(XlsxCellWriter writer, UInt16 value, XlsxSerializerOptions options)
            => writer.Write(value);
    }

}

namespace FlatXlsx.Providers
{
    public sealed partial class PrimitiveXlsxSerializerProvider
    {
        internal partial void InitPrimitives()
        {
            serializers[typeof(System.Boolean)] = new FlatXlsx.Serializers.BooleanXlsxSerializer();
            serializers[typeof(System.Byte)] = new FlatXlsx.Serializers.ByteXlsxSerializer();
            serializers[typeof(System.SByte)] = new FlatXlsx.Serializers.SByteXlsxSerializer();
            serializers[typeof(System.Decimal)] = new FlatXlsx.Serializers.DecimalXlsxSerializer();
            serializers[typeof(System.Double)] = new FlatXlsx.Serializers.DoubleXlsxSerializer();
            serializers[typeof(System.Single)] = new FlatXlsx.Serializers.SingleXlsxSerializer();
            serializers[typeof(System.Int32)] = new FlatXlsx.Serializers.Int32XlsxSerializer();
            serializers[typeof(System.UInt32)] = new FlatXlsx.Serializers.UInt32XlsxSerializer();
            serializers[typeof(System.Int64)] = new FlatXlsx.Serializers.Int64XlsxSerializer();
            serializers[typeof(System.UInt64)] = new FlatXlsx.Serializers.UInt64XlsxSerializer();
            serializers[typeof(System.Int16)] = new FlatXlsx.Serializers.Int16XlsxSerializer();
            serializers[typeof(System.UInt16)] = new FlatXlsx.Serializers.UInt16XlsxSerializer();
        }
    }
}