// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY `Serializers/PrimitiveSerializer.tt`. DO NOT CHANGE IT.
// </auto-generated>
#nullable enable
namespace FlatXlsx.Serializers
{
    public sealed class BooleanExcelSerializer : IExcelSerializer<Boolean>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, Boolean value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, Boolean value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class ByteExcelSerializer : IExcelSerializer<Byte>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, Byte value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, Byte value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class SByteExcelSerializer : IExcelSerializer<SByte>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, SByte value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, SByte value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class DecimalExcelSerializer : IExcelSerializer<Decimal>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, Decimal value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, Decimal value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class DoubleExcelSerializer : IExcelSerializer<Double>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, Double value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, Double value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class SingleExcelSerializer : IExcelSerializer<Single>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, Single value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, Single value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class Int32ExcelSerializer : IExcelSerializer<Int32>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, Int32 value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, Int32 value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class UInt32ExcelSerializer : IExcelSerializer<UInt32>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, UInt32 value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, UInt32 value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class Int64ExcelSerializer : IExcelSerializer<Int64>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, Int64 value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, Int64 value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class UInt64ExcelSerializer : IExcelSerializer<UInt64>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, UInt64 value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, UInt64 value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class Int16ExcelSerializer : IExcelSerializer<Int16>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, Int16 value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, Int16 value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

    public sealed class UInt16ExcelSerializer : IExcelSerializer<UInt16>
    {        
		public void WriteTitle(ref ExcelSerializerWriter writer, UInt16 value, ExcelSerializerOptions options, string name = "value")
            => writer.Write(name);

        public void Serialize(ref ExcelSerializerWriter writer, UInt16 value, ExcelSerializerOptions options)
            => writer.WritePrimitive(value);
    }

}

namespace FlatXlsx.Providers
{
    public sealed partial class PrimitiveExcelSerializerProvider
    {
        internal partial void InitPrimitives()
        {
            serializers[typeof(System.Boolean)] = new FlatXlsx.Serializers.BooleanExcelSerializer();
            serializers[typeof(System.Byte)] = new FlatXlsx.Serializers.ByteExcelSerializer();
            serializers[typeof(System.SByte)] = new FlatXlsx.Serializers.SByteExcelSerializer();
            serializers[typeof(System.Decimal)] = new FlatXlsx.Serializers.DecimalExcelSerializer();
            serializers[typeof(System.Double)] = new FlatXlsx.Serializers.DoubleExcelSerializer();
            serializers[typeof(System.Single)] = new FlatXlsx.Serializers.SingleExcelSerializer();
            serializers[typeof(System.Int32)] = new FlatXlsx.Serializers.Int32ExcelSerializer();
            serializers[typeof(System.UInt32)] = new FlatXlsx.Serializers.UInt32ExcelSerializer();
            serializers[typeof(System.Int64)] = new FlatXlsx.Serializers.Int64ExcelSerializer();
            serializers[typeof(System.UInt64)] = new FlatXlsx.Serializers.UInt64ExcelSerializer();
            serializers[typeof(System.Int16)] = new FlatXlsx.Serializers.Int16ExcelSerializer();
            serializers[typeof(System.UInt16)] = new FlatXlsx.Serializers.UInt16ExcelSerializer();
        }
    }
}