// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY `Serializers/TupleSerializers.tt`. DO NOT CHANGE IT.
// </auto-generated>
// Derived from Cysharp/WebSerializer (MIT License, Copyright (c) 2022 Cysharp, Inc.).
// See THIRD-PARTY-NOTICES.txt in the repository root.
#nullable enable
namespace FlatXlsx.Serializers
{
    public sealed class TupleXlsxSerializer<T1> : IXlsxSerializer<Tuple<T1>>
    {
		public void WriteTitle(XlsxCellWriter writer, Tuple<T1> value, XlsxSerializerOptions options, string name = "value"){
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            writer.ExitNested();
        }
        public void Serialize(XlsxCellWriter writer, Tuple<T1> value, XlsxSerializerOptions options)
        {
            if (value == null) {
                writer.WriteEmpty();
                return;
            }
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            writer.ExitNested();
        }
    }

    public sealed class ValueTupleXlsxSerializer<T1> : IXlsxSerializer<ValueTuple<T1>>
    {
		public void WriteTitle(XlsxCellWriter writer, ValueTuple<T1> value, XlsxSerializerOptions options, string name = "value"){
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            writer.ExitNested();
        }
        }
        public void Serialize(XlsxCellWriter writer, ValueTuple<T1> value, XlsxSerializerOptions options)
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            writer.ExitNested();
        }
    }

    public sealed class TupleXlsxSerializer<T1, T2> : IXlsxSerializer<Tuple<T1, T2>>
    {
		public void WriteTitle(XlsxCellWriter writer, Tuple<T1, T2> value, XlsxSerializerOptions options, string name = "value"){
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            writer.ExitNested();
        }
        public void Serialize(XlsxCellWriter writer, Tuple<T1, T2> value, XlsxSerializerOptions options)
        {
            if (value == null) {
                writer.WriteEmpty();
                return;
            }
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            writer.ExitNested();
        }
    }

    public sealed class ValueTupleXlsxSerializer<T1, T2> : IXlsxSerializer<ValueTuple<T1, T2>>
    {
		public void WriteTitle(XlsxCellWriter writer, ValueTuple<T1, T2> value, XlsxSerializerOptions options, string name = "value"){
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            writer.ExitNested();
        }
        }
        public void Serialize(XlsxCellWriter writer, ValueTuple<T1, T2> value, XlsxSerializerOptions options)
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            writer.ExitNested();
        }
    }

    public sealed class TupleXlsxSerializer<T1, T2, T3> : IXlsxSerializer<Tuple<T1, T2, T3>>
    {
		public void WriteTitle(XlsxCellWriter writer, Tuple<T1, T2, T3> value, XlsxSerializerOptions options, string name = "value"){
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            writer.ExitNested();
        }
        public void Serialize(XlsxCellWriter writer, Tuple<T1, T2, T3> value, XlsxSerializerOptions options)
        {
            if (value == null) {
                writer.WriteEmpty();
                return;
            }
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            writer.ExitNested();
        }
    }

    public sealed class ValueTupleXlsxSerializer<T1, T2, T3> : IXlsxSerializer<ValueTuple<T1, T2, T3>>
    {
		public void WriteTitle(XlsxCellWriter writer, ValueTuple<T1, T2, T3> value, XlsxSerializerOptions options, string name = "value"){
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            writer.ExitNested();
        }
        }
        public void Serialize(XlsxCellWriter writer, ValueTuple<T1, T2, T3> value, XlsxSerializerOptions options)
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            writer.ExitNested();
        }
    }

    public sealed class TupleXlsxSerializer<T1, T2, T3, T4> : IXlsxSerializer<Tuple<T1, T2, T3, T4>>
    {
		public void WriteTitle(XlsxCellWriter writer, Tuple<T1, T2, T3, T4> value, XlsxSerializerOptions options, string name = "value"){
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            options.GetRequiredSerializer<T4>().WriteTitle(writer, value.Item4, options, $"{name}4");
            writer.ExitNested();
        }
        public void Serialize(XlsxCellWriter writer, Tuple<T1, T2, T3, T4> value, XlsxSerializerOptions options)
        {
            if (value == null) {
                writer.WriteEmpty();
                return;
            }
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            options.GetRequiredSerializer<T4>().Serialize(writer, value.Item4, options);
            writer.ExitNested();
        }
    }

    public sealed class ValueTupleXlsxSerializer<T1, T2, T3, T4> : IXlsxSerializer<ValueTuple<T1, T2, T3, T4>>
    {
		public void WriteTitle(XlsxCellWriter writer, ValueTuple<T1, T2, T3, T4> value, XlsxSerializerOptions options, string name = "value"){
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            options.GetRequiredSerializer<T4>().WriteTitle(writer, value.Item4, options, $"{name}4");
            writer.ExitNested();
        }
        }
        public void Serialize(XlsxCellWriter writer, ValueTuple<T1, T2, T3, T4> value, XlsxSerializerOptions options)
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            options.GetRequiredSerializer<T4>().Serialize(writer, value.Item4, options);
            writer.ExitNested();
        }
    }

    public sealed class TupleXlsxSerializer<T1, T2, T3, T4, T5> : IXlsxSerializer<Tuple<T1, T2, T3, T4, T5>>
    {
		public void WriteTitle(XlsxCellWriter writer, Tuple<T1, T2, T3, T4, T5> value, XlsxSerializerOptions options, string name = "value"){
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            options.GetRequiredSerializer<T4>().WriteTitle(writer, value.Item4, options, $"{name}4");
            options.GetRequiredSerializer<T5>().WriteTitle(writer, value.Item5, options, $"{name}5");
            writer.ExitNested();
        }
        public void Serialize(XlsxCellWriter writer, Tuple<T1, T2, T3, T4, T5> value, XlsxSerializerOptions options)
        {
            if (value == null) {
                writer.WriteEmpty();
                return;
            }
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            options.GetRequiredSerializer<T4>().Serialize(writer, value.Item4, options);
            options.GetRequiredSerializer<T5>().Serialize(writer, value.Item5, options);
            writer.ExitNested();
        }
    }

    public sealed class ValueTupleXlsxSerializer<T1, T2, T3, T4, T5> : IXlsxSerializer<ValueTuple<T1, T2, T3, T4, T5>>
    {
		public void WriteTitle(XlsxCellWriter writer, ValueTuple<T1, T2, T3, T4, T5> value, XlsxSerializerOptions options, string name = "value"){
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            options.GetRequiredSerializer<T4>().WriteTitle(writer, value.Item4, options, $"{name}4");
            options.GetRequiredSerializer<T5>().WriteTitle(writer, value.Item5, options, $"{name}5");
            writer.ExitNested();
        }
        }
        public void Serialize(XlsxCellWriter writer, ValueTuple<T1, T2, T3, T4, T5> value, XlsxSerializerOptions options)
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            options.GetRequiredSerializer<T4>().Serialize(writer, value.Item4, options);
            options.GetRequiredSerializer<T5>().Serialize(writer, value.Item5, options);
            writer.ExitNested();
        }
    }

    public sealed class TupleXlsxSerializer<T1, T2, T3, T4, T5, T6> : IXlsxSerializer<Tuple<T1, T2, T3, T4, T5, T6>>
    {
		public void WriteTitle(XlsxCellWriter writer, Tuple<T1, T2, T3, T4, T5, T6> value, XlsxSerializerOptions options, string name = "value"){
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            options.GetRequiredSerializer<T4>().WriteTitle(writer, value.Item4, options, $"{name}4");
            options.GetRequiredSerializer<T5>().WriteTitle(writer, value.Item5, options, $"{name}5");
            options.GetRequiredSerializer<T6>().WriteTitle(writer, value.Item6, options, $"{name}6");
            writer.ExitNested();
        }
        public void Serialize(XlsxCellWriter writer, Tuple<T1, T2, T3, T4, T5, T6> value, XlsxSerializerOptions options)
        {
            if (value == null) {
                writer.WriteEmpty();
                return;
            }
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            options.GetRequiredSerializer<T4>().Serialize(writer, value.Item4, options);
            options.GetRequiredSerializer<T5>().Serialize(writer, value.Item5, options);
            options.GetRequiredSerializer<T6>().Serialize(writer, value.Item6, options);
            writer.ExitNested();
        }
    }

    public sealed class ValueTupleXlsxSerializer<T1, T2, T3, T4, T5, T6> : IXlsxSerializer<ValueTuple<T1, T2, T3, T4, T5, T6>>
    {
		public void WriteTitle(XlsxCellWriter writer, ValueTuple<T1, T2, T3, T4, T5, T6> value, XlsxSerializerOptions options, string name = "value"){
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            options.GetRequiredSerializer<T4>().WriteTitle(writer, value.Item4, options, $"{name}4");
            options.GetRequiredSerializer<T5>().WriteTitle(writer, value.Item5, options, $"{name}5");
            options.GetRequiredSerializer<T6>().WriteTitle(writer, value.Item6, options, $"{name}6");
            writer.ExitNested();
        }
        }
        public void Serialize(XlsxCellWriter writer, ValueTuple<T1, T2, T3, T4, T5, T6> value, XlsxSerializerOptions options)
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            options.GetRequiredSerializer<T4>().Serialize(writer, value.Item4, options);
            options.GetRequiredSerializer<T5>().Serialize(writer, value.Item5, options);
            options.GetRequiredSerializer<T6>().Serialize(writer, value.Item6, options);
            writer.ExitNested();
        }
    }

    public sealed class TupleXlsxSerializer<T1, T2, T3, T4, T5, T6, T7> : IXlsxSerializer<Tuple<T1, T2, T3, T4, T5, T6, T7>>
    {
		public void WriteTitle(XlsxCellWriter writer, Tuple<T1, T2, T3, T4, T5, T6, T7> value, XlsxSerializerOptions options, string name = "value"){
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            options.GetRequiredSerializer<T4>().WriteTitle(writer, value.Item4, options, $"{name}4");
            options.GetRequiredSerializer<T5>().WriteTitle(writer, value.Item5, options, $"{name}5");
            options.GetRequiredSerializer<T6>().WriteTitle(writer, value.Item6, options, $"{name}6");
            options.GetRequiredSerializer<T7>().WriteTitle(writer, value.Item7, options, $"{name}7");
            writer.ExitNested();
        }
        public void Serialize(XlsxCellWriter writer, Tuple<T1, T2, T3, T4, T5, T6, T7> value, XlsxSerializerOptions options)
        {
            if (value == null) {
                writer.WriteEmpty();
                return;
            }
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            options.GetRequiredSerializer<T4>().Serialize(writer, value.Item4, options);
            options.GetRequiredSerializer<T5>().Serialize(writer, value.Item5, options);
            options.GetRequiredSerializer<T6>().Serialize(writer, value.Item6, options);
            options.GetRequiredSerializer<T7>().Serialize(writer, value.Item7, options);
            writer.ExitNested();
        }
    }

    public sealed class ValueTupleXlsxSerializer<T1, T2, T3, T4, T5, T6, T7> : IXlsxSerializer<ValueTuple<T1, T2, T3, T4, T5, T6, T7>>
    {
		public void WriteTitle(XlsxCellWriter writer, ValueTuple<T1, T2, T3, T4, T5, T6, T7> value, XlsxSerializerOptions options, string name = "value"){
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            options.GetRequiredSerializer<T4>().WriteTitle(writer, value.Item4, options, $"{name}4");
            options.GetRequiredSerializer<T5>().WriteTitle(writer, value.Item5, options, $"{name}5");
            options.GetRequiredSerializer<T6>().WriteTitle(writer, value.Item6, options, $"{name}6");
            options.GetRequiredSerializer<T7>().WriteTitle(writer, value.Item7, options, $"{name}7");
            writer.ExitNested();
        }
        }
        public void Serialize(XlsxCellWriter writer, ValueTuple<T1, T2, T3, T4, T5, T6, T7> value, XlsxSerializerOptions options)
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            options.GetRequiredSerializer<T4>().Serialize(writer, value.Item4, options);
            options.GetRequiredSerializer<T5>().Serialize(writer, value.Item5, options);
            options.GetRequiredSerializer<T6>().Serialize(writer, value.Item6, options);
            options.GetRequiredSerializer<T7>().Serialize(writer, value.Item7, options);
            writer.ExitNested();
        }
    }

    public sealed class TupleXlsxSerializer<T1, T2, T3, T4, T5, T6, T7, TRest> : IXlsxSerializer<Tuple<T1, T2, T3, T4, T5, T6, T7, TRest>>
        where TRest : notnull
    {
		public void WriteTitle(XlsxCellWriter writer, Tuple<T1, T2, T3, T4, T5, T6, T7, TRest> value, XlsxSerializerOptions options, string name = "value"){
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            options.GetRequiredSerializer<T4>().WriteTitle(writer, value.Item4, options, $"{name}4");
            options.GetRequiredSerializer<T5>().WriteTitle(writer, value.Item5, options, $"{name}5");
            options.GetRequiredSerializer<T6>().WriteTitle(writer, value.Item6, options, $"{name}6");
            options.GetRequiredSerializer<T7>().WriteTitle(writer, value.Item7, options, $"{name}7");
            options.GetRequiredSerializer<TRest>().WriteTitle(writer, value.Rest, options, $"{name}8");
            writer.ExitNested();
        }
        public void Serialize(XlsxCellWriter writer, Tuple<T1, T2, T3, T4, T5, T6, T7, TRest> value, XlsxSerializerOptions options)
        {
            if (value == null) {
                writer.WriteEmpty();
                return;
            }
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            options.GetRequiredSerializer<T4>().Serialize(writer, value.Item4, options);
            options.GetRequiredSerializer<T5>().Serialize(writer, value.Item5, options);
            options.GetRequiredSerializer<T6>().Serialize(writer, value.Item6, options);
            options.GetRequiredSerializer<T7>().Serialize(writer, value.Item7, options);
            options.GetRequiredSerializer<TRest>().Serialize(writer, value.Rest, options);
            writer.ExitNested();
        }
    }

    public sealed class ValueTupleXlsxSerializer<T1, T2, T3, T4, T5, T6, T7, TRest> : IXlsxSerializer<ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest>>
        where TRest : struct
    {
		public void WriteTitle(XlsxCellWriter writer, ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest> value, XlsxSerializerOptions options, string name = "value"){
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().WriteTitle(writer, value.Item1, options, name);
            options.GetRequiredSerializer<T2>().WriteTitle(writer, value.Item2, options, $"{name}2");
            options.GetRequiredSerializer<T3>().WriteTitle(writer, value.Item3, options, $"{name}3");
            options.GetRequiredSerializer<T4>().WriteTitle(writer, value.Item4, options, $"{name}4");
            options.GetRequiredSerializer<T5>().WriteTitle(writer, value.Item5, options, $"{name}5");
            options.GetRequiredSerializer<T6>().WriteTitle(writer, value.Item6, options, $"{name}6");
            options.GetRequiredSerializer<T7>().WriteTitle(writer, value.Item7, options, $"{name}7");
            options.GetRequiredSerializer<TRest>().WriteTitle(writer, value.Rest, options, $"{name}8");
            writer.ExitNested();
        }
        }
        public void Serialize(XlsxCellWriter writer, ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest> value, XlsxSerializerOptions options)
        {
            writer.EnterNested();
            options.GetRequiredSerializer<T1>().Serialize(writer, value.Item1, options);
            options.GetRequiredSerializer<T2>().Serialize(writer, value.Item2, options);
            options.GetRequiredSerializer<T3>().Serialize(writer, value.Item3, options);
            options.GetRequiredSerializer<T4>().Serialize(writer, value.Item4, options);
            options.GetRequiredSerializer<T5>().Serialize(writer, value.Item5, options);
            options.GetRequiredSerializer<T6>().Serialize(writer, value.Item6, options);
            options.GetRequiredSerializer<T7>().Serialize(writer, value.Item7, options);
            options.GetRequiredSerializer<TRest>().Serialize(writer, value.Rest, options);
            writer.ExitNested();
        }
    }


    internal static class TupleXlsxSerializer
    {
        internal static Type GetTupleXlsxSerializerType(int i)
        {
            switch (i)
            {
                case 1:
                    return typeof(TupleXlsxSerializer<>);
                case 2:
                    return typeof(TupleXlsxSerializer<,>);
                case 3:
                    return typeof(TupleXlsxSerializer<,,>);
                case 4:
                    return typeof(TupleXlsxSerializer<,,,>);
                case 5:
                    return typeof(TupleXlsxSerializer<,,,,>);
                case 6:
                    return typeof(TupleXlsxSerializer<,,,,,>);
                case 7:
                    return typeof(TupleXlsxSerializer<,,,,,,>);
                case 8:
                    return typeof(TupleXlsxSerializer<,,,,,,,>);
                default:
                    break;
            }

            throw new InvalidOperationException(SR.TupleSerializerNotFound(i));
        }

        internal static Type GetValueTupleXlsxSerializerType(int i)
        {
            switch (i)
            {
                case 1:
                    return typeof(ValueTupleXlsxSerializer<>);
                case 2:
                    return typeof(ValueTupleXlsxSerializer<,>);
                case 3:
                    return typeof(ValueTupleXlsxSerializer<,,>);
                case 4:
                    return typeof(ValueTupleXlsxSerializer<,,,>);
                case 5:
                    return typeof(ValueTupleXlsxSerializer<,,,,>);
                case 6:
                    return typeof(ValueTupleXlsxSerializer<,,,,,>);
                case 7:
                    return typeof(ValueTupleXlsxSerializer<,,,,,,>);
                case 8:
                    return typeof(ValueTupleXlsxSerializer<,,,,,,,>);
                default:
                    break;
            }

            throw new InvalidOperationException(SR.TupleSerializerNotFound(i));
        }
    }
}